name: mp_project
description: Bluebook-style mobile UI subset
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.4
  path: ^1.9.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  image_picker: ^1.0.7
  flutter_math_fork: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
